/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RaffleContractInterface extends Interface {
  getFunction(
    nameOrSignature: "getExistingStudents" | "raffleStudents"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RaffleDone"): EventFragment;

  encodeFunctionData(
    functionFragment: "getExistingStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raffleStudents",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExistingStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raffleStudents",
    data: BytesLike
  ): Result;
}

export namespace RaffleDoneEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RaffleContract extends BaseContract {
  connect(runner?: ContractRunner | null): RaffleContract;
  waitForDeployment(): Promise<this>;

  interface: RaffleContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getExistingStudents: TypedContractMethod<[], [string[]], "view">;

  raffleStudents: TypedContractMethod<
    [_numberOfStudents: BigNumberish],
    [string[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getExistingStudents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "raffleStudents"
  ): TypedContractMethod<[_numberOfStudents: BigNumberish], [string[]], "view">;

  getEvent(
    key: "RaffleDone"
  ): TypedContractEvent<
    RaffleDoneEvent.InputTuple,
    RaffleDoneEvent.OutputTuple,
    RaffleDoneEvent.OutputObject
  >;

  filters: {
    "RaffleDone(address)": TypedContractEvent<
      RaffleDoneEvent.InputTuple,
      RaffleDoneEvent.OutputTuple,
      RaffleDoneEvent.OutputObject
    >;
    RaffleDone: TypedContractEvent<
      RaffleDoneEvent.InputTuple,
      RaffleDoneEvent.OutputTuple,
      RaffleDoneEvent.OutputObject
    >;
  };
}
