/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as raffleSol from "./Raffle.sol";
export type { raffleSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { RaffleContract } from "./Raffle.sol/RaffleContract";
export { RaffleContract__factory } from "./factories/Raffle.sol/RaffleContract__factory";
